# 基本配置/Basic settings
title: Website Title # 博客网站标题/Title of the blog
intro: >- # 关于博客的简介/Introduction of the blog
  This is my blog. I will share some of my thoughts and experiences here.
blurb: >- # 关于你的简介/Introduction of yourself
  Hi there. I'm Steven, a student from China.
baseurl: "" # 根目录，默认留空即可，但如果你的网站没有部署在根目录，则需要手动修改。/Root directory, leave it blank by default, but if your website is not deployed in the root directory, you need to modify it manually.
username: Your name # 你的博客署名。/Your blog author.
markdown: kramdown # Markdown解析器/Markdown parser
highlighter: rouge # 代码高亮/Code highlight
kramdown:
  input: GFM # GFM: Github Flavored Markdown
  syntax_highlighter: rouge # 代码高亮/Code highlight
timezone: Asia/Shanghai # 时区/Timezone

# 你的社交账号或联系方式，这些信息将会出现在博客的底部，没有的不填即可。
# Your social account or contact information, which will appear at the bottom of the blog. If not, please leave it blank.
email: # 邮箱/Email
github_account: # Github账号/Github account
twitter_account: # Twitter账号/Twitter account
facebook_account: # Facebook账号/Facebook account
instagram_account: # Instagram账号/Instagram account
linkedin_account: # 领英账号/Linkedin account
zhihu_account: # 知乎账号/Zhihu account(A Chinese Q&A website)
weibo_account: # 微博账号(微博账号，不是微博id)/Weibo account(A Chinese social media platform)

# Build配置/Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude: # Jekyll构建时应该被排除的文件/Files that should be excluded when Jekyll is built
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
# jekyll-paginate配置。/jekyll-paginate settings.
paginate: 5 # 每页显示的文章数量/Number of articles displayed per page
paginate_path: "/page/:num/" # 分页的URL格式/Paging URL format

# 本项目的一些配置。/Some settings of this project.
lang: zh-CN # ( <html lang=""> ) html元素的lang特性。/HTML element lang attribute.
localization: CN # 本地化显示，可选项：EN(英文), CN(简体中文), TC(繁体中文), 其他缺省为英文。/Localization display, optional: EN (English), CN (Simplified Chinese), TC (Traditional Chinese), other defaults to English.
# 文章简介的样式，如果你喜欢在每篇文章前写一个“blockquote”作为引言(> XXX)，建议使用这种样式，否则建议用“"post.content | strip_html | truncatewords: 50"”
# The style of the article introduction, if you like to write a "blockquote" as a quotation before each article (> XXX), it is recommended to use this style, otherwise it is recommended to use '"post.content | strip_html | truncatewords: 50"'
article_introduction_format: post.excerpt
article_catalogue: true # 是否在侧边菜单展示文章目录/Whether to display the article catalogue in the sidebar menu

# 评论功能配置/Comment settings
gitalk: # Gitalk(https://github.com/gitalk/gitalk)相关配置，请自行修改。/Gitalk settings, please modify it.
  enable: true # 是否启用Gitalk/Whether to enable Gitalk
  clientID:
  clientSecret:
  repo:
  owner:
disqus: # 目前暂不支持disqus/Disqus is not supported yet.
  enable: false # Disqus

# 其他插件配置/Other plugins settings
simple-jekyll-search: # Simple Jekyll Search(搜索功能)
  enable: true # 是否启用搜索/Whether to enable search
  results_limit: 10 # 搜索结果的显示上限/Display limit of search results
mathjax: # MathJax(数学公式)
  enable: true # 是否允许渲染数学公式/Whether to enable render formula
jekyll-mermaid: # Jekyll Mermaid(绘图功能)
  enable: true # 是否启用绘图功能/Whether to enable drawing function
